-- AlterTable
ALTER TABLE "Poi" ADD COLUMN IF NOT EXISTS "yelpId" TEXT;
ALTER TABLE "Poi" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION;
ALTER TABLE "Poi" ADD COLUMN IF NOT EXISTS "priceLevel" TEXT;
ALTER TABLE "Poi" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
ALTER TABLE "Poi" ADD COLUMN IF NOT EXISTS "yelpUrl" TEXT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Poi_yelpId_key" ON "Poi"("yelpId");
